version: '3.1'

services:
  client:
    build: .
    image: twitu/git-scores-client:latest
    volumes:
      - "./client:/app"
    ports:
      - "80:3000"
    depends_on:
      - server

  server:
    build: .
    image: twitu/git-scores-server:latest
    volumes:
      - "./server:/app"
    ports:
      - "8080"
